# Author:      Luca Postregna <lavish@gmail.com>
# License:     MIT, see LICENSE for details

import os
import time, datetime

site_name = "iulii.net"
author = "lucapost"
src_dir = "sources"
dst_dir = "site"
prefix = "/"
home = "home"
path_separator = "/"
src_ext = {"markdown": "md", "textile": "tt", "plain": "txt"}
dst_ext = "html"
hidden = set(["404.md", "500.md", "search.md"])

current_time = datetime.datetime.now()
menu_code = ''

def menu(node):
	global menu_code

	menu_code = '\n'
	root = node
	while root.parent:
		root = root.parent
	menu_(root, node)
	return menu_code

def menu_(node, cur_node, node_prefix = prefix, indent = ''):
	global menu_code

	menu_code += indent + '<ul>\n'
	for child in sorted(node.children, key=lambda n: n.src_pathname):
		if child.dst_file.startswith("index.") or child.src_file in hidden:
			continue
		menu_code += indent + '<li class="level-' + str(child.level) + '"><a '
		if(child == cur_node
		or (cur_node.dst_file.startswith("index.") and child == cur_node.parent)):
			menu_code += 'class="current" '
		menu_code += 'href="' + node_prefix + child.dst_file
		if child.children:
			menu_code += "/index." + dst_ext + '">'	+ child.name + '</a>\n'
			menu_(child, cur_node, node_prefix + child.dst_file + '/', indent + '\t')
			menu_code += indent + '</li>\n'
		else:
			menu_code += '">'   + child.name + '</a></li>\n'
	menu_code += indent + '</ul>\n'

def header(node):
	"""Builds the header and returns it to a string."""
	
	return '''<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="author" content="''' + author + '''" />
		<link rel="stylesheet" type="text/css" media="all" href="/css/reset.css" />
		<link rel="stylesheet" type="text/css" media="all" href="/css/text.css" />
		<link rel="stylesheet" type="text/css" media="all" href="/css/960.css" />
		<title>''' + site_name + ' | ' + node.name + '''</title>
	</head>
	<body>
		<div id="container">
			<header>
				<h1><a href="''' + '../' * node.level + '''index.''' + dst_ext + '''">''' + site_name + '''</a></h1>
			</header>
			<div id="path">
				path: %%%PATH%%%
			</div>
			<div id="main">
				<nav>
					''' + menu(node) + '''
				</nav>
				<div id="content">
'''

def footer(node):
	"""Builds the footer and returns it to a string."""

	return '''
				</div>
				<div id="edit">
					Last edit: ''' + time.strftime("%m/%d/%Y %I:%M:%S %p",time.localtime(os.path.getmtime(node.src_pathname))) + '''
				</div>
			</div>
			<footer>
				&copy; ''' + str(current_time.year) + ' ' + author + ''' | Generated by <a href="http://www.minimalblue.com/projects/minimalsite.html">minimalsite</a> 
			</footer>
		</div>
	</body>
</html>'''
